version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    dependencies:
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
