test:
  - test/**/*

github_actions:
  - .github/**/*

code style:
  - .editorconfig

docs:
  - README.md
  - doc/**/*

arrango-db:
  - src/HealthChecks.ArangoDb/**/*

aws:
  - src/HealthChecks.Aws.*/**/*

azure:
  - src/HealthChecks.Azure*/**/*

consul:
  - src/HealthChecks.Consul/**/*

kafka:
  - src/HealthChecks.Kafka/**/*

UI:
  - src/HealthChecks.UI/**/*
  - src/HealthChecks.UI.*/**/*
