name: HealthChecks SignalR CD

on:
  push:
    tags:
      - release-signalr-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.SignalR/HealthChecks.SignalR.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.SignalR
