name: HealthChecks Publisher.ApplicationInsights CD

on:
  push:
    tags:
      - release-publisher_applicationinsights-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Publisher.ApplicationInsights/HealthChecks.Publisher.ApplicationInsights.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Publisher.ApplicationInsights
