name: HealthChecks Uris CD

on:
  push:
    tags:
      - release-uris-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Uris/HealthChecks.Uris.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Uris
