name: HealthChecks SQL Server DB CD

on:
  push:
    tags:
      - release-sqlserver-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.SqlServer
