name: HealthChecks NPGSQL DB CD

on:
  push:
    tags:
      - release-npgsql-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.NpgSql/HealthChecks.NpgSql.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.NpgSql
