name: HealthChecks AzureDigitalTwin CD

on:
  push:
    tags:
      - release-azure_digitaltwin-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.AzureDigitalTwin/HealthChecks.AzureDigitalTwin.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.AzureDigitalTwin
