name: HealthChecks Kubernetes CD

on:
  push:
    tags:
      - release-kubernetes-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Kubernetes/HealthChecks.Kubernetes.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Kubernetes
