name: HealthChecks Milvus CD

on:
  push:
    tags:
      - release-milvus-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Milvus/HealthChecks.Milvus.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Milvus
