name: HealthChecks Kafka CD

on:
  push:
    tags:
      - release-kafka-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Kafka/HealthChecks.Kafka.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Kafka
