name: HealthChecks Publisher.Prometheus Preview CD

on:
  push:
    tags:
      - preview-publisher_prometheus-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Publisher.Prometheus/HealthChecks.Publisher.Prometheus.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Publisher.Prometheus
