name: HealthChecks Publisher.OpenTelemetry CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.OpenTelemetry/**
      - test/HealthChecks.Publisher.OpenTelemetry.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_publisher_opentelemetry_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
    tags-ignore:
      - release-*
      - preview-*

  pull_request:
    branches: [ master ]
    paths:
      - src/HealthChecks.Publisher.OpenTelemetry/**
      - test/HealthChecks.Publisher.OpenTelemetry.Tests/**
      - test/_SHARED/**
      - .github/workflows/healthchecks_publisher_opentelemetry_ci.yml
      - .github/workflows/reusable_ci_workflow.yml
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props

jobs:
  build:
    uses: ./.github/workflows/reusable_ci_workflow.yml
    with:
      PROJECT_PATH: ./src/HealthChecks.Publisher.OpenTelemetry/HealthChecks.Publisher.OpenTelemetry.csproj
      TEST_PROJECT_PATH: ./test/HealthChecks.Publisher.OpenTelemetry.Tests/HealthChecks.Publisher.OpenTelemetry.Tests.csproj
      CODECOV_FLAGS: Publisher.OpenTelemetry
