name: HealthChecks Elastic Search CD

on:
  push:
    tags:
      - release-elasticsearch-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Elasticsearch/HealthChecks.Elasticsearch.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Elasticsearch
