name: HealthChecks Sqlite CD

on:
  push:
    tags:
      - release-sqlite-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Sqlite/HealthChecks.Sqlite.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Sqlite
