name: HealthChecks DynamoDb CD

on:
  push:
    tags:
      - release-dynamodb-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.DynamoDb/HealthChecks.DynamoDb.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.DynamoDb
