name: HealthChecks Aws Systems Manager Preview CD

on:
  push:
    tags:
      - preview-aws_systemsmanager-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Aws.SystemsManager/HealthChecks.Aws.SystemsManager.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Aws.SystemsManager
