name: HealthChecks SurrealDB CD

on:
  push:
    tags:
      - release-surrealdb-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.SurrealDb/HealthChecks.SurrealDb.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.SurrealDb
