name: HealthChecks CassandraDb CD

on:
  push:
    tags:
      - release-cassandradb-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.CassandraDb/HealthChecks.CassandraDb.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.CassandraDb
