name: HealthChecks Publisher.ApplicationInsights Preview CD

on:
  push:
    tags:
      - preview-publisher_applicationinsights-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Publisher.ApplicationInsights/HealthChecks.Publisher.ApplicationInsights.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Publisher.ApplicationInsights
