name: HealthChecks IbmMQ CD

on:
  push:
    tags:
      - release-ibmq-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.IbmMQ/HealthChecks.IbmMQ.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.IbmMQ
