name: HealthChecks Aws.S3 CD

on:
  push:
    tags:
      - release-aws_s3-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Aws.S3/HealthChecks.Aws.S3.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Aws.S3
