name: HealthChecks RavenDb Preview CD

on:
  push:
    tags:
      - preview-ravendb-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.RavenDB/HealthChecks.RavenDB.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.RavenDB
