name: HealthChecks Publisher.OpenTelemetry CD

on:
  push:
    tags:
      - release-publisher_opentelemetry-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Publisher.OpenTelemetry/HealthChecks.Publisher.OpenTelemetry.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Publisher.OpenTelemetry
