name: HealthChecks Nats CD

on:
  push:
    tags:
      - release-nats-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Nats/HealthChecks.Nats.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Nats
