name: HealthChecks SQL Server DB Preview CD

on:
  push:
    tags:
      - preview-sqlserver-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.SqlServer
