name: HealthChecks Publisher.Seq CD

on:
  push:
    tags:
      - release-publisher_seq-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Publisher.Seq/HealthChecks.Publisher.Seq.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Publisher.Seq
