name: HealthChecks Consul CD

on:
  push:
    tags:
      - release-consul-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Consul/HealthChecks.Consul.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Consul
