name: HealthChecks Prometheus.Metrics CD

on:
  push:
    tags:
      - release-prometheus_metrics-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Prometheus.Metrics/HealthChecks.Prometheus.Metrics.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Prometheus.Metrics
