name: HealthChecks MySql Preview CD

on:
  push:
    tags:
      - preview-mysql-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.MySql/HealthChecks.MySql.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.MySql
