name: HealthChecks AzureApplicationInsights CD

on:
  push:
    tags:
      - release-azureapplicationinsights-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.AzureApplicationInsights/HealthChecks.AzureApplicationInsights.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.AzureApplicationInsights
