name: HealthChecks Qdrant CD

on:
  push:
    tags:
      - release-qdrant-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Qdrant/HealthChecks.Qdrant.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Qdrant
