name: HealthChecks ClickHouse DB CD

on:
  push:
    tags:
      - release-clickhouse-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.ClickHouse/HealthChecks.ClickHouse.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.ClickHouse
