name: HealthChecks Azure KeyVault Secrets Preview CD

on:
  push:
    tags:
      - preview-azurekeyvault-secrets-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Azure.KeyVault.Secrets/HealthChecks.Azure.KeyVault.Secrets.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Azure.KeyVault.Secrets