name: HealthChecks Publisher.Datadog CD

on:
  push:
    tags:
      - release-publisher_datadog-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Publisher.Datadog/HealthChecks.Publisher.Datadog.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Publisher.Datadog
