name: HealthChecks Redis CD

on:
  push:
    tags:
      - release-redis-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Redis
