name: HealthChecks System CD

on:
  push:
    tags:
      - release-system-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.System/HealthChecks.System.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.System
