name: HealthChecks EventStore.gRPC Preview CD

on:
  push:
    tags:
      - preview-eventstore_grpc-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.EventStore.gRPC/HealthChecks.EventStore.gRPC.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.EventStore.gRPC
