name: HealthChecks Redis Preview CD

on:
  push:
    tags:
      - preview-redis-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Redis/HealthChecks.Redis.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Redis
