name: HealthChecks Application Status CD

on:
  push:
    tags:
      - release-applicationstatus-*
      - release-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      PROJECT_PATH: ./src/HealthChecks.ApplicationStatus/HealthChecks.ApplicationStatus.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.ApplicationStatus
