name: HealthChecks Aws Sqs Preview CD

on:
  push:
    tags:
      - preview-aws_sqs-*
      - preview-all-*

jobs:
  build:
    uses: ./.github/workflows/reusable_cd_preview_workflow.yml
    secrets: inherit
    with:
      BUILD_CONFIG: Release
      VERSION_SUFFIX_PREFIX: rc1
      PROJECT_PATH: ./src/HealthChecks.Aws.Sqs/HealthChecks.Aws.Sqs.csproj
      PACKAGE_NAME: AspNetCore.HealthChecks.Aws.Sqs
